"""Add individual goals support with quarter, approval, and freezing fields

Revision ID: 1edccf6e74f0
Revises: d7f139b94d7f
Create Date: 2025-11-05 08:14:31.351217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1edccf6e74f0'
down_revision: Union[str, None] = 'd7f139b94d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Commented out task table drops - keeping old task data for reference
    # op.drop_index('ix_task_submissions_id', table_name='task_submissions')
    # op.drop_table('task_submissions')
    # op.drop_index('ix_task_documents_id', table_name='task_documents')
    # op.drop_table('task_documents')
    # op.drop_index('ix_tasks_id', table_name='tasks')
    # op.drop_table('tasks')
    # op.drop_index('ix_task_extensions_id', table_name='task_extensions')
    # op.drop_table('task_extensions')
    # op.drop_index('ix_task_assignments_id', table_name='task_assignments')
    # op.drop_table('task_assignments')
    op.add_column('goals', sa.Column('quarter', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='quarter'), nullable=True))
    op.add_column('goals', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('goals', sa.Column('frozen', sa.Boolean(), nullable=True))
    op.add_column('goals', sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('goals', sa.Column('frozen_by', sa.UUID(), nullable=True))
    op.add_column('goals', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('goals', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('goals', sa.Column('owner_id', sa.UUID(), nullable=True))

    # Set default values for existing goals
    op.execute('UPDATE goals SET frozen = FALSE WHERE frozen IS NULL')

    op.create_foreign_key(None, 'goals', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'goals', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'goals', 'users', ['frozen_by'], ['id'])
    op.drop_index('ix_initiative_assignments_initiative_user', table_name='initiative_assignments')
    op.drop_constraint('initiative_assignments_initiative_id_fkey', 'initiative_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'initiative_assignments', 'initiatives', ['initiative_id'], ['id'])
    op.drop_index('ix_initiative_documents_initiative', table_name='initiative_documents')
    op.drop_constraint('initiative_documents_initiative_id_fkey', 'initiative_documents', type_='foreignkey')
    op.create_foreign_key(None, 'initiative_documents', 'initiatives', ['initiative_id'], ['id'])
    op.drop_index('ix_initiative_extensions_initiative', table_name='initiative_extensions')
    op.drop_constraint('initiative_extensions_initiative_id_fkey', 'initiative_extensions', type_='foreignkey')
    op.create_foreign_key(None, 'initiative_extensions', 'initiatives', ['initiative_id'], ['id'])
    op.drop_index('ix_initiative_submissions_initiative', table_name='initiative_submissions')
    op.drop_constraint('initiative_submissions_initiative_id_fkey', 'initiative_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'initiative_submissions', 'initiatives', ['initiative_id'], ['id'])
    op.drop_index('ix_initiatives_assigned_by', table_name='initiatives')
    op.drop_index('ix_initiatives_created_by', table_name='initiatives')
    op.drop_index('ix_initiatives_status', table_name='initiatives')
    op.drop_index('idx_review_traits_organization_id', table_name='review_traits')
    op.drop_index('idx_review_traits_scope', table_name='review_traits')
    op.drop_constraint('fk_review_traits_organization_id', 'review_traits', type_='foreignkey')
    op.create_foreign_key(None, 'review_traits', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_traits', type_='foreignkey')
    op.create_foreign_key('fk_review_traits_organization_id', 'review_traits', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_review_traits_scope', 'review_traits', ['scope_type', 'organization_id'], unique=False)
    op.create_index('idx_review_traits_organization_id', 'review_traits', ['organization_id'], unique=False)
    op.create_index('ix_initiatives_status', 'initiatives', ['status'], unique=False)
    op.create_index('ix_initiatives_created_by', 'initiatives', ['created_by'], unique=False)
    op.create_index('ix_initiatives_assigned_by', 'initiatives', ['assigned_by'], unique=False)
    op.drop_constraint(None, 'initiative_submissions', type_='foreignkey')
    op.create_foreign_key('initiative_submissions_initiative_id_fkey', 'initiative_submissions', 'initiatives', ['initiative_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_initiative_submissions_initiative', 'initiative_submissions', ['initiative_id'], unique=False)
    op.drop_constraint(None, 'initiative_extensions', type_='foreignkey')
    op.create_foreign_key('initiative_extensions_initiative_id_fkey', 'initiative_extensions', 'initiatives', ['initiative_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_initiative_extensions_initiative', 'initiative_extensions', ['initiative_id'], unique=False)
    op.drop_constraint(None, 'initiative_documents', type_='foreignkey')
    op.create_foreign_key('initiative_documents_initiative_id_fkey', 'initiative_documents', 'initiatives', ['initiative_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_initiative_documents_initiative', 'initiative_documents', ['initiative_id'], unique=False)
    op.drop_constraint(None, 'initiative_assignments', type_='foreignkey')
    op.create_foreign_key('initiative_assignments_initiative_id_fkey', 'initiative_assignments', 'initiatives', ['initiative_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_initiative_assignments_initiative_user', 'initiative_assignments', ['initiative_id', 'user_id'], unique=False)
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'owner_id')
    op.drop_column('goals', 'approved_by')
    op.drop_column('goals', 'approved_at')
    op.drop_column('goals', 'rejection_reason')
    op.drop_column('goals', 'frozen_by')
    op.drop_column('goals', 'frozen_at')
    op.drop_column('goals', 'frozen')
    op.drop_column('goals', 'year')
    op.drop_column('goals', 'quarter')
    # Commented out task table recreations - not dropping them in upgrade
    # op.create_table('task_assignments',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_assignments_task_id_fkey'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='task_assignments_user_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='task_assignments_pkey')
    # )
    # op.create_index('ix_task_assignments_id', 'task_assignments', ['id'], unique=False)
    # op.create_table('task_extensions',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('new_due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'DENIED', name='extensionstatus'), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name='task_extensions_requested_by_fkey'),
    # sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='task_extensions_reviewed_by_fkey'),
    # sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_extensions_task_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='task_extensions_pkey')
    # )
    # op.create_index('ix_task_extensions_id', 'task_extensions', ['id'], unique=False)
    # op.create_table('tasks',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('type', postgresql.ENUM('INDIVIDUAL', 'GROUP', name='tasktype'), autoincrement=False, nullable=False),
    # sa.Column('urgency', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskurgency'), autoincrement=False, nullable=True),
    # sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('status', postgresql.ENUM('PENDING', 'ONGOING', 'COMPLETED', 'PENDING_REVIEW', 'APPROVED', 'OVERDUE', name='taskstatus'), autoincrement=False, nullable=True),
    # sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('team_head_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('goal_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='tasks_created_by_fkey'),
    # sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name='tasks_goal_id_fkey'),
    # sa.ForeignKeyConstraint(['team_head_id'], ['users.id'], name='tasks_team_head_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='tasks_pkey'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    # op.create_table('task_documents',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    # sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_documents_task_id_fkey'),
    # sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='task_documents_uploaded_by_fkey'),
    # sa.PrimaryKeyConstraint('id', name='task_documents_pkey')
    # )
    # op.create_index('ix_task_documents_id', 'task_documents', ['id'], unique=False)
    # op.create_table('task_submissions',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('report', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('submitted_by', sa.UUID(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name='task_submissions_submitted_by_fkey'),
    # sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_submissions_task_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='task_submissions_pkey')
    # )
    # op.create_index('ix_task_submissions_id', 'task_submissions', ['id'], unique=False)
    # ### end Alembic commands ###
