"""initial migration

Revision ID: 309b649ccb3b
Revises: 
Create Date: 2025-09-30 11:03:35.080793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309b649ccb3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_performance_scores_band', table_name='performance_scores')
    op.drop_index('idx_performance_scores_cycle', table_name='performance_scores')
    op.drop_index('idx_performance_scores_user', table_name='performance_scores')
    op.create_index(op.f('ix_performance_scores_id'), 'performance_scores', ['id'], unique=False)
    op.drop_index('idx_review_assignments_cycle', table_name='review_assignments')
    op.drop_index('idx_review_assignments_reviewee', table_name='review_assignments')
    op.drop_index('idx_review_assignments_reviewer', table_name='review_assignments')
    op.drop_index('idx_review_assignments_status', table_name='review_assignments')
    op.create_index(op.f('ix_review_assignments_id'), 'review_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_review_cycle_traits_id'), 'review_cycle_traits', ['id'], unique=False)
    op.drop_index('idx_review_questions_trait', table_name='review_questions')
    op.create_index(op.f('ix_review_questions_id'), 'review_questions', ['id'], unique=False)
    op.drop_index('idx_review_responses_assignment', table_name='review_responses')
    op.create_index(op.f('ix_review_responses_id'), 'review_responses', ['id'], unique=False)
    op.alter_column('review_scores', 'self_score',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('review_scores', 'peer_score',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('review_scores', 'supervisor_score',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('review_scores', 'weighted_score',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.drop_index('idx_review_scores_cycle_user', table_name='review_scores')
    op.create_index(op.f('ix_review_scores_id'), 'review_scores', ['id'], unique=False)
    op.drop_index('idx_review_traits_active', table_name='review_traits')
    op.drop_index('idx_review_traits_display_order', table_name='review_traits')
    op.create_index(op.f('ix_review_traits_id'), 'review_traits', ['id'], unique=False)
    op.alter_column('task_documents', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tasks', 'urgency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskurgency'),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_index('idx_users_level_rank', table_name='users')
    op.drop_index('idx_users_supervisor_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_supervisor_id', 'users', ['supervisor_id'], unique=False)
    op.create_index('idx_users_level_rank', 'users', ['level_rank'], unique=False)
    op.alter_column('tasks', 'urgency',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskurgency'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('task_documents', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_review_traits_id'), table_name='review_traits')
    op.create_index('idx_review_traits_display_order', 'review_traits', ['display_order'], unique=False)
    op.create_index('idx_review_traits_active', 'review_traits', ['is_active'], unique=False)
    op.drop_index(op.f('ix_review_scores_id'), table_name='review_scores')
    op.create_index('idx_review_scores_cycle_user', 'review_scores', ['cycle_id', 'user_id'], unique=False)
    op.alter_column('review_scores', 'weighted_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('review_scores', 'supervisor_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('review_scores', 'peer_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('review_scores', 'self_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_review_responses_id'), table_name='review_responses')
    op.create_index('idx_review_responses_assignment', 'review_responses', ['assignment_id'], unique=False)
    op.drop_index(op.f('ix_review_questions_id'), table_name='review_questions')
    op.create_index('idx_review_questions_trait', 'review_questions', ['trait_id'], unique=False)
    op.drop_index(op.f('ix_review_cycle_traits_id'), table_name='review_cycle_traits')
    op.drop_index(op.f('ix_review_assignments_id'), table_name='review_assignments')
    op.create_index('idx_review_assignments_status', 'review_assignments', ['status'], unique=False)
    op.create_index('idx_review_assignments_reviewer', 'review_assignments', ['reviewer_id'], unique=False)
    op.create_index('idx_review_assignments_reviewee', 'review_assignments', ['reviewee_id'], unique=False)
    op.create_index('idx_review_assignments_cycle', 'review_assignments', ['cycle_id'], unique=False)
    op.drop_index(op.f('ix_performance_scores_id'), table_name='performance_scores')
    op.create_index('idx_performance_scores_user', 'performance_scores', ['user_id'], unique=False)
    op.create_index('idx_performance_scores_cycle', 'performance_scores', ['cycle_id'], unique=False)
    op.create_index('idx_performance_scores_band', 'performance_scores', ['performance_band'], unique=False)
    # ### end Alembic commands ###
